pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
}
rootProject.name = "KotlinExtensions"
include("ktx-base64")
include("ktx-comparator")
include("ktx-compose")
include("ktx-compose-constraint-layout")
include("ktx-compose-accompanist")
include("ktx-compose-image")
include("ktx-compose-resource")
include("ktx-coroutine")
include("ktx-datetime")
include("ktx-function")
include("ktx-geometry")
include("ktx-intent")
include("ktx-intl")
include("ktx-kodein-db")
include("ktx-ktor-client")
include("ktx-library")
include("ktx-livedata")
include("ktx-logging")
include("ktx-molecule")
include("ktx-moshi")
include("ktx-preference")
include("ktx-resource")
include("ktx-serialization")
include("ktx-serialization-compose")
include("ktx-settings")
include("ktx-settings-compose")
include("ktx-value")
