package com.bselzer.ktx.client.connectivity

enum class CapabilityType(val code: Int) {
    MMS(0),
    SUPL(1),
    DUN(2),
    FOTA(3),
    IMS(4),
    CBS(5),
    WIFI_P2P(6),
    IA(7),
    RCS(8),
    XCAP(9),
    EIMS(10),
    METERED(11),
    INTERNET(12),
    RESTRICTED(13),
    TRUSTED(14),
    NOT_VPN(15),
    VALIDATED(16),
    CAPTIVE_PORTAL(17),
    NOT_ROAMING(18),
    FOREGROUND(19),
    NOT_CONGESTED(20),
    NOT_SUSPENDED(21),
    MCX(23),
    TEMPORARY_NOT_METERED(25),
    ENTERPRISE(29),
    HEAD_UNIT(32)
}