[versions]
androidx-compose = "1.4.2"
kotlin = "1.8.10"
ktor = "2.3.0"
ktx-serialization = "1.5.0"
moko-resources = "0.22.0"
multiplatform-compose = "1.3.1"
multiplatform-compose-compiler = "1.4.2"
multiplatform-settings = "1.0.0"

[libraries]
about-libraries = { group = "com.mikepenz", name = "aboutlibraries-core", version = "10.6.2" }
android-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.0.3" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.10.0" }
androidx-test-compose-ui = { group = "androidx.compose.ui", name = "ui-test", version.ref = "androidx-compose" }
androidx-test-compose-ui-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose" }
androidx-test-core = { group = "androidx.test", name = "core", version = "1.5.0" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.5" }
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.5.2" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "multiplatform-compose" }
compose-material = { group = "org.jetbrains.compose.material", name = "material", version.ref = "multiplatform-compose" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "multiplatform-compose" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "multiplatform-compose" }
compose-ui-util = { group = "org.jetbrains.compose.ui", name = "ui-util", version.ref = "multiplatform-compose" }
kodein-db = { group = "org.kodein.db", name = "kodein-db-api", version = "0.9.0-beta" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test-common", version.ref = "kotlin" }
kotlin-test-annotations = { group = "org.jetbrains.kotlin", name = "kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
ktor-client = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.4.0" }
ktx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "ktx-serialization" }
ktx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "ktx-serialization" }
ktx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.6.4" }
moko-resources = { group = "dev.icerock.moko", name = "resources", version.ref = "moko-resources" }
moko-resources-compose = { group = "dev.icerock.moko", name = "resources-compose", version.ref = "moko-resources" }
moko-resources-generator = { group = "dev.icerock.moko", name = "resources-generator", version.ref = "moko-resources" }
napier = { group = "io.github.aakira", name = "napier", version = "2.6.1" }
robolectric = { group = "org.robolectric", name = "robolectric", version = "4.10" }
settings = { group = "com.russhwolf", name = "multiplatform-settings", version.ref = "multiplatform-settings" }
settings-coroutines = { group = "com.russhwolf", name = "multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
xml-serialization = { group = "io.github.pdvrieze.xmlutil", name = "serialization", version = "0.85.0" }

[bundles]
android-unit-test = ["kotlin-test-junit", "androidx-test-core", "androidx-test-junit", "androidx-test-runner", "robolectric", "kotlin-reflect", "androidx-test-compose-ui", "androidx-test-compose-ui-junit"]
common = ["kotlin-stdlib"]
common-test = ["kotlin-test", "kotlin-test-annotations"]
compose = ["compose-foundation", "compose-material", "compose-runtime", "compose-ui", "compose-ui-util"]
jvm-test = ["kotlin-test-junit", "kotlin-reflect"]
settings = ["settings", "settings-coroutines"]

# TODO can't NOT provide a version and use alias for plugins already in the classpath https://github.com/gradle/gradle/issues/17968
[plugins]
android-library = { id = "com.android.library" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform" }
compose = { id = "org.jetbrains.compose", version.ref = "multiplatform-compose" }
ktx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-resources" }